apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./flux-system
- cbs-authentication-deploy-service.yaml
- nginx.yaml


#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization
#resources:
#- ./flux-system #- gotk-components.yaml
#- gotk-sync.yaml
#- cbs-authentication-deploy-service.yaml
